### ISSUE TITLE
Question interne

### ISSUE THREAD

**Issue by loulou123546** [Le-Bouc-Fou/Snakeur#1]
Quand le joueur va trop à gauche, se TP t-il à droite ou meurt t-il ?
@Le-Bouc-Fou/graphics

**Comment by LeBoucFouYT** [comment]
C'est un jeu 2d ?

**Comment by LeBoucFouYT** [comment]
Pas tout compris ^^

**Comment by loulou123546** [comment]
Je pense que sa sera plus simple de faire en 2D.

Quand le joueur va vers la gauche et qu'il touche le mur,  
soit il fait comme dans pac-man et il passe de gauche à droite, soit il meurt.

Je met quoi dans le moteur de jeu ?

**Comment by LeBoucFouYT** [comment]
Meurt !!!!!

**Comment by LeBoucFouYT** [comment]
Voilà xD

**Comment by LeBoucFouYT** [comment]
Du coup faut que je regarde pour les map en 2D ^^

**Comment by loulou123546** [comment]
ok

oui tous est dans l'onglet `Projects`
